### ISSUE TITLE
key with dot are not parsed properly

### ISSUE THREAD

**Issue by deivh** [leonelquinteros/php-toml#14]
(( Thank you for the great job ! I really like your implementation :+1:  ))

(from the toml guide:)

name = "Orange"
physical.color = "orange"
physical.shape = "round"
site."google.com" = true

In JSON we should have:

{
  "name": "Orange",
  "physical": {
    "color": "orange",
    "shape": "round"
  },
  "site": {
    "google.com": true
  }
}

instead we have:

[name] => Orange
[physical.color] => orange
[physical.shape] => round
[site."google.com"] => true

**Comment by leonelquinteros** [comment]
Thanks for reporting! Sorry to be this late =)

This is fixed by https://github.com/leonelquinteros/php-toml/commit/33e0157ff38626d39f0fe71d642301a320a12fc3
