### ISSUE TITLE
Does not parse inline tables

### ISSUE THREAD

**Issue by tobia** [leonelquinteros/php-toml#5]
This file:

    [tab1]
    foo = {bar='Donald Duck'}

should be parsed as:

    [
        "tab1" => [
            "foo" => [
                "bar" => 'Donald Duck',
            ],
        ],
    ]

instead of:

    [
        "tab1" => [
            "foo" => "{bar='Donald Duck'}",
        ],
    ]

**Comment by leonelquinteros** [comment]
@tobia Thanks again for taking the time to test and report this issues. 

This one wasn't even implemented. I did a quick implementation for it.
