### ISSUE TITLE
Does not parse arrays of tables correctly

### ISSUE THREAD

**Issue by tobia** [leonelquinteros/php-toml#6]
This file:

    [fruit]
    name = "apple"

    [[fruit.variety]]
    name = "red delicious"

    [[fruit.variety]]
    name = "granny smith"

should be parsed as:

    [
        "fruit" => [
            "name" => "apple",
            "variety" => [
                0 => [
                   "name" => "red delicious",
                ],
                1 => [
                    "name" => "granny smith",
                ],
            ],
        ],
    ]

Instead of this strange thing:

    [
        "fruit" => [
            "name" => "apple",
            0 => [],
            1 => [
                "variety" => [
                    [
                        "name" => "red delicious",
                    ],
                ],
            ],
            2 => [],
            3 => [
                "variety" => [
                    [
                        "name" => "granny smith",
                    ],
                ],
            ],
        ],
    ]

By the way, it should also work without the initial section:

    [[fruit.variety]]
    name = "red delicious"

    [[fruit.variety]]
    name = "granny smith"

in which case it should give the same array as above, without the `"name" => "apple"` line.

**Comment by leonelquinteros** [comment]
@tobia Thanks for reporting. 

This one is fixed now.
