### ISSUE TITLE
Not working with UTF-8 BOM

### ISSUE THREAD

**Issue by davidlueder** [leonelquinteros/php-toml#7]
If the file contains an UTF-8 Byte Order Mark, Toml::parseFile(...) throws an error.

Fix: Use this code:

> public static function parseFile($path)
> {
>     if(!is_file($path))
>     {
>         throw new Exception('Invalid file path');
>     }
>     $toml = self::remove_utf8_bom(file_get_contents($path));
>     return self::parse($toml);
> }
> public static function remove_utf8_bom($text)
> {
>     $bom = pack('H*','EFBBBF');
>     $text = preg_replace("/^$bom/", '', $text);
>     return $text;
> }

instead of this:
> public static function parseFile($path)
> {
>     if(!is_file($path))
>     {
>         throw new Exception('Invalid file path');
>     }
>     $toml = file_get_contents($path);
>     return self::parse($toml);
> }

**Comment by leonelquinteros** [comment]
Thanks for reporting @davidlueder ! 

Now it parses files with BOM correctly. 
Feel free to send a Pull Request any time.
