### ISSUE TITLE
escaping check

### ISSUE THREAD

**Issue by MikhailMarchenko** [leonelquinteros/php-toml#8]
`371    elseif($toml[$i] == "\\" && !in_array($toml[$i+1], array('b', 't', 'n', 'f', 'r', 'u', 'U', '"', "\\", ' ')))`

when check string like "SERVER\\\\MASTER"
got error \M not allowed, but \\\\ is allowed. why dont we skip next to M (mean i++) instead?

**Comment by leonelquinteros** [comment]
Nice catch! Thanks for reporting. 

It should be fixed now, i'm rolling out a new minor release to include this fix.
